// Fill out your copyright notice in the Description page of Project Settings.


#include "Projectile.h"
#include "Components/BoxComponent.h"
#include "Particles/ParticleSystemComponent.h"
#include "Particles/ParticleSystem.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundCue.h"
#include "Blaster/Blaster.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraComponent.h"
#include "Blaster/Enemy/Enemy.h"

AProjectile::AProjectile()
{
 	
	PrimaryActorTick.bCanEverTick = true;
	bReplicates = true;//to spawn on the client and till control on the server we will replicate it here

	CollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("CollisionBox"));
	SetRootComponent(CollisionBox);
	CollisionBox->SetCollisionObjectType(ECollisionChannel::ECC_WorldDynamic);
	CollisionBox->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	CollisionBox->SetCollisionResponseToAllChannels(ECollisionResponse::ECR_Ignore);
	CollisionBox->SetCollisionResponseToChannel(ECollisionChannel::ECC_Visibility, ECollisionResponse::ECR_Block);
	CollisionBox->SetCollisionResponseToChannel(ECollisionChannel::ECC_WorldStatic, ECollisionResponse::ECR_Block);
	//CollisionBox->SetCollisionResponseToChannel(ECollisionChannel::ECC_Pawn, ECollisionResponse::ECR_Block);
	CollisionBox->SetCollisionResponseToChannel(ECC_SkeletalMesh, ECollisionResponse::ECR_Block);


}


void AProjectile::BeginPlay()
{
	Super::BeginPlay();
	if (Tracer)
	{
		TracerComponent=UGameplayStatics::SpawnEmitterAttached(
		Tracer,
		CollisionBox,
		FName(),
		GetActorLocation(),
		GetActorRotation(),
		EAttachLocation::KeepWorldPosition);
	}
	
	
		CollisionBox->OnComponentHit.AddDynamic(this,&ThisClass::OnHit);
	
	
}

void AProjectile::StartDestroyTimer()
{
	GetWorldTimerManager().SetTimer(DestroyTimer, this, &ThisClass::DestroyTimerFinished, DestroyTime);
}

void AProjectile::ExplodeDamage()
{
	
	APawn* FiringPawn = GetInstigator();
	if (FiringPawn)
	{
		AController* FiringControlller = FiringPawn->GetController();
		if (FiringControlller )//Applying Damage On the server
		{
			UGameplayStatics::ApplyRadialDamageWithFalloff(
				this,// world context object
				Damage, //Base Damage
				10.f,//Minimum Damage
				GetActorLocation(),//Origin
				DamageInnerRadius,//DamageInnerRadius
				DamageOuterRadius,//DamageOuterRadius
				1.f,//Damage Falloff
				UDamageType::StaticClass(),//Damage Type
				TArray<AActor*>(),//ignore actors
				this,//DamageCauser
				FiringControlller//FiringController
			);
		}
	}
}

void AProjectile::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit)
{
	
	Destroy();//this is call by this name
}

void AProjectile::SpawnTrailSystem()
{
	if (TrailSystem)
	{
		TrailSystemComponent = UNiagaraFunctionLibrary::SpawnSystemAttached(
			TrailSystem,
			GetRootComponent(),
			FName(),
			GetActorLocation(),
			GetActorRotation(),
			EAttachLocation::KeepWorldPosition,
			false
		);
	}
}


void AProjectile::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}

void AProjectile::Destroyed()//this function will  replicate the projectile to all clients because it is replicated actor so we are taking advantage of it thus data will be propagated to all the client sfrom the server ,so we do not need to create the Multicast RPC
{
	Super::Destroyed();
	if (ImpactPoint)
	{
		UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), ImpactPoint, GetActorTransform());
	}
	if (ImpactSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, ImpactSound, GetActorLocation());

	}
	
}


void AProjectile::DestroyTimerFinished()
{
	Destroy();
}